<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Target Framework                                                      │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Version                                                       │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <Version>2.0.0-preview.1</Version>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Package Info.                                                        │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <Authors>Wolf Bublitz</Authors>
    <Description>Common base types for WB.Logging.</Description>
    <PackageTags>WB.Logging</PackageTags>
    <PackageProjectUrl>https://github.com/WolfBublitz/WB.Logging</PackageProjectUrl>
    <RepositoryUrl>https://github.com/WolfBublitz/WB.Logging</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Nullability Settings                                                 │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Local Project Directory                                                              │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <LocalProjectDependencies>$(MSBuildThisFileDirectory)deps/</LocalProjectDependencies>
  </PropertyGroup>

</Project>