<Project>
  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Central Package Management                                           │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ WB Packages                                                          │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageVersion Include="WB.Logging.Base" Version="[1.0.0-preview.14, 2.0.0)" />
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ 3rd-Party Packages                                                   │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageVersion Include="MinVer" Version="[7.0.0, 8)" />
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Test Packages                                                        │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageVersion Include="WB.CodeAnalyzer" Version="1.0.0" />
    <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
    <PackageVersion Include="AwesomeAssertions.Analyzers" Version="9.0.8" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.0.2" />
    <PackageVersion Include="TUnit" Version="1.43.11" />
    <PackageVersion Include="Verify" Version="31.16.1" />
    <PackageVersion Include="Verify.TUnit" Version="31.16.1" />
  </ItemGroup>
</Project>
