<Project Sdk="Microsoft.NET.Sdk">

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Package Info.                                                        │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <Authors>Wolf Bublitz</Authors>
    <Description>A simple logging library for .NET.</Description>
    <PackageTags>logger, logging, .NET</PackageTags>
    <PackageProjectUrl>https://github.com/WolfBublitz/WB.Logging</PackageProjectUrl>
    <RepositoryUrl>https://github.com/WolfBublitz/WB.Logging</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Build Settings                                                       │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Analyzer Settings                                                    │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WB.CodeAnalyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Documentation                                                        │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Source Link.                                                         │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <EnableSourceLink>true</EnableSourceLink>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <EnableSourceLink>false</EnableSourceLink>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
	     │ Deterministic Builds                                                 │
	     ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Deterministic>false</Deterministic>
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Debug Settings                                                       │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ README                                                               │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ LICENSE                                                              │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../LICENSE.txt" Pack="true" PackagePath="" />
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Package References                                                   │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup Condition="'$(UseLocalProjects)' != 'true'">
    <PackageReference Include="WB.Logging.Base" />
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Project References                                                   │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup Condition="'$(UseLocalProjects)' == 'true'">
    <ProjectReference Include="$(PathToLocalProjects)WB.Logging.Base/src/WB.Logging.Base.csproj" />
  </ItemGroup>

</Project>