name: 👩🏻‍🔬 Test

on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: true 
        type: string
      tests:
        required: true
        type: string
        description: 'JSON array of test names'

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.collect.outputs.projects }}
    steps:
      - uses: actions/checkout@v4

      - id: collect
        name: 🔍 Discover Test Projects
        run: |
          projects=$(find . -name "*Tests.csproj" | jq -R -s -c 'split("\n")[:-1]')
          echo "projects=$projects" >> $GITHUB_OUTPUT

  test:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.discover.outputs.projects) }}
    
    steps:
    - uses: actions/checkout@v4

    - name: 🔧 Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: 🔄 Restore
      working-directory: src
      run: dotnet restore
    
    - name: 👩🏻‍🔬 Test
      run: dotnet run ${{ matrix.project }} --no-restore --configuration Release --report-trx
    
    - name: 📢 Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: tests/**/*.trx
